export const DEFAULT_CONTINUITY_INTERVAL_MINUTES = 55;
export const MIN_CONTINUITY_INTERVAL_MINUTES = 1;
export const DEFAULT_CONTINUITY_INTERVAL_MS = DEFAULT_CONTINUITY_INTERVAL_MINUTES * 60 * 1000;
